"""empty message

Revision ID: 6b189126a11c
Revises: 18c45299b957
Create Date: 2022-08-04 16:21:25.838554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b189126a11c'
down_revision = '18c45299b957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'create_time')
    # ### end Alembic commands ###
